apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest         # Corrigido alinhamento
          imagePullPolicy: Never         # Corrigido alinhamento
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: http://backend:3000
            - name: NEXTAUTH_URL
              value: http://localhost:3000
            - name: NEXTAUTH_SECRET
              value: super-nextauth-secret
