apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest   # Altere caso tenha um nome diferente
          imagePullPolicy: Never  # <-- Adicione para usar imagem local
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@meu-postgres-postgresql:5432/minha_base
            - name: JWT_SECRET
              value: super-secret-key
          command: ["sh", "-c", "npm install && npx prisma generate && npx prisma migrate deploy && npm start"]
