name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [frontend, backend]

    defaults:
      run:
        working-directory: ./${{ matrix.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Lint
        run: |
          if [ -f "package.json" ]; then
            npm run lint || true
          fi

      - name: Run Prettier Check
        run: |
          if [ -f "package.json" ]; then
            npx prettier --check . || true
          fi

      - name: Run Tests
        run: |
          if [ -f "package.json" ]; then
            npm run test || true
          fi

      - name: Build Project
        run: |
          if [ -f "package.json" ]; then
            npm run build || true
          fi

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test-lint

    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        service: [frontend, backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/residencia-${{ matrix.service }}:latest ./${{ matrix.service }}
          docker push ghcr.io/${{ github.repository_owner }}/residencia-${{ matrix.service }}:latest
