name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    name: Trivy Scan (Container and Dependencies)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images (frontend)
        run: |
          docker build -t frontend:latest ./frontend

      - name: Build Docker images (backend)
        run: |
          docker build -t backend:latest ./backend

      - name: Run Trivy vulnerability scan on frontend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: frontend:latest
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Run Trivy vulnerability scan on backend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: backend:latest
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Trivy scan on frontend dependencies
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: ./frontend
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Trivy scan on backend dependencies
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: ./backend
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH
